### ISSUE TITLE
FastMenu bug

### ISSUE THREAD

**Issue by Wikinger8** [Kyuuhachi/VencordPlugins#1]
When I use FastMenu, I cannot delete text or voice channels.

**Comment by Kyuuhachi** [comment]
I can't reproduce this — at least "delete channel" in the right click menu works for me. Which makes sense, because there's no reason that would be affected by that plugin. Is it some other delete channel button you're talking about?

Some other troubleshooting steps to try:
- does it happen with eager loading disabled?
- is anything printed in the devtools log?

**Comment by Wikinger8** [comment]
![image](https://github.com/Kyuuhachi/VencordPlugins/assets/85295145/c8a4deca-a2d0-42a5-bdde-88cbbbbf2980)
I get this error in console and it makes no difference if I use eager loading or not.

**Comment by Kyuuhachi** [comment]
That doesn't look like it should be relevant. Sentry is just tracking and error reporting, shouldn't have anything to do with ui at all.

**Comment by Wikinger8** [comment]
https://github.com/Kyuuhachi/VencordPlugins/assets/85295145/2fd2f962-d2cf-4324-98b4-548fb82f7237

**Comment by thororen1234** [comment]
> c.mp4

this is not to do with fastmenu as it works just fine on my end.

**Comment by Kyuuhachi** [comment]
No, I can confirm the issue (regardless of whether eager loading is on or not). After some investigation, this code is to blame:
```js
onConfirm={() => {
	props.onClose();
	_25.ComponentDispatch.subscribeOnce(
		_30.ComponentActions.LAYER_POP_COMPLETE,
		() => _5.deleteChannel(channel.id),
	);
	_6.popLayer();
}}
```

In other words, it's waiting for the layer remove animation to finish before deleting the channel. The animation that this plugin removes. Guess I'll have to figure out how to send that event.
